### ISSUE TITLE
Database issue upgrading from 2020012300 to 2020031800 (at commit af03ae5)

### ISSUE THREAD

**Issue by pennedav** [catalyst/moodle-tool_crawler#125] opened 2020-03-18 18:55 UTC
See screenshot. I'll submit a pull request for the fix shortly.

<img width="1145" alt="screenshot" src="https://user-images.githubusercontent.com/1786996/76996405-d667f680-6927-11ea-8d05-d489386846f8.png">

**Comment by kristian-94** [comment] 2020-03-19 02:20
Hi @pennedav , I have tried to reproduce this by installing the commit just before, 18ab64b03fa264d0216b14129a5643272f3d7006

and then checking out master and running this upgrade. But it finishes successfully. What version of moodle are you on?

**Comment by pennedav** [comment] 2020-03-19 13:33
@kristian-94 Moodle 3.8+ (Build: 20191212) (Version: 2019111800.05)

**Comment by kristian-94** [comment] 2020-03-20 02:14
@pennedav  I got this output from the latest moodle 3.8, it seems to work there. (This is upgrading from 08a3e7b75b to af03ae5 crawler commits).

> root@89dc35d8f49a:/siteroot# php admin/cli/upgrade.php 
> == Upgrading Moodle database from version 3.8.2+ (Build: 20200312) (2019111802.01) to 3.8.2+ (Build: 20200312) (2019111802.01) ==
> 
> Your Moodle files have been changed, and you are about to automatically
> upgrade your server to this version:
> 
> 3.8.2+ (BUILD: 20200312) (2019111802.01)
> 
> Once you do this you can not go back again. Please note that this process
> can take a long time.
> 
> Are you sure you want to upgrade this server to this version?
> 
> type y (means yes) or n (means no)
> : y
> -->tool_crawler
> ++ 2020031800: Success (0.24 seconds) ++
> ++ Success (0.32 seconds) ++
> == Setting new default values ==
> New setting: outgoingmailconfig_noreplyaddress
> Command line upgrade from 3.8.2+ (Build: 20200312) (2019111802.01) to 3.8.2+ (Build: 20200312) (2019111802.01) completed successfully.

I also went and found your moodle version, commit 3bfdc05d3a668947debc27c8100da213261e706d of the MOODLE_38_STABLE branch

and it also works there, this is my output:

> root@89dc35d8f49a:/siteroot# php admin/cli/upgrade.php 
> == Upgrading Moodle database from version 3.8+ (Build: 20191212) (2019111800.05) to 3.8+ (Build: 20191212) (2019111800.05) ==
> 
> Your Moodle files have been changed, and you are about to automatically
> upgrade your server to this version:
> 
> 3.8+ (BUILD: 20191212) (2019111800.05)
> 
> Once you do this you can not go back again. Please note that this process
> can take a long time.
> 
> Are you sure you want to upgrade this server to this version?
> 
> type y (means yes) or n (means no)
> : y
> -->tool_crawler
> ++ 2020031800: Success (0.06 seconds) ++
> ++ Success (0.12 seconds) ++
> == Setting new default values ==
> New setting: outgoingmailconfig_noreplyaddress
> Command line upgrade from 3.8+ (Build: 20191212) (2019111800.05) to 3.8+ (Build: 20191212) (2019111800.05) completed successfully.


Maybe there is something messed up in your database. Can you run `php admin/cli/check_database_schema.php`  and see if there is anything amiss there.

**Comment by pennedav** [comment] 2020-03-23 22:20
@kristian-94 I've tested this again on a completely fresh instance of Moodle (no extra plugins other than this one and the prerequisite auth_basic plugin) on a completely fresh database. Upgrading from 08a3e7b to af03ae5 on Moodle 3.8 at 3bfdc05 with the same error during the upgrade. The error occurs whether or not the upgrade happens from the web UI or with the CLI upgrade script. Running `check_database_schema.php` prior to upgrading the code or running the upgrade reports the database is OK:

<img width="1053" alt="001" src="https://user-images.githubusercontent.com/1786996/77368388-8081bd00-6d32-11ea-88ae-932fbd0f91c4.png">

I then upgrade the plugin code, attempt to upgrade and see the usual error:

<img width="1576" alt="002" src="https://user-images.githubusercontent.com/1786996/77368458-a3ac6c80-6d32-11ea-8194-e9f96ca5cef0.png">

Running `check_database_schema.php` immediately thereafter reports missing fields:

<img width="875" alt="003" src="https://user-images.githubusercontent.com/1786996/77368520-bfb00e00-6d32-11ea-8f99-d8a4a262c374.png">

Hope this helps.

**Comment by kristian-94** [comment] 2020-03-24 03:35
I did the same test plan as you did here, but no error for me.

I think the issue is a mysql vs postgres thing, I can see you are on mysql. I'll have to switch to mysql and see if that causes it.

**Comment by kristian-94** [comment] 2020-03-24 05:09
I also get the error on mysql. And your change fixes it, and doesn't cause issues for postgres, so thank you for that. I will try to get that merged in today

**Comment by kristian-94** [comment] 2020-03-24 23:59
Thanks for reporting this, I have merged that in and updated in the plugins directory. :+1:

**Closed by kristian-94** 2020-03-24 23:59 UTC
